### ISSUE TITLE
Fact check

### ISSUE THREAD

**Issue by leondz** [qntm/base131072#10]
Hi,

The readme states:

> We need 131,586 "safe" characters for this encoding, but as of Unicode 9.0 only 108,397 exist.

unicode.org states:

> "Unicode 15.0 adds 4,489 characters, for a total of 149,186 characters." [link](https://www.unicode.org/versions/Unicode15.0.0/)

Are some of these newer characters non-safe?

**Comment by qntm** [comment]
As of Unicode 15.0 there are 128,811 safe characters. For a full table of the number of safe characters in each version of Unicode, see [here](https://qntm.org/safe). I just updated the table for Unicode 15.0.
