### ISSUE TITLE
Unicode 16.0 has been released, don't we have enough safe characters now?

### ISSUE THREAD

**Issue by PhMajerus** [qntm/base131072#13]
[Unicode 16.0](https://www.unicode.org/versions/Unicode16.0.0/) added 5185 characters, including 3995 Hieroglyphs that seem to be all individual glyphs, no normalization or combining characters, as well as hundredth of other characters in other blocks.
Doesn't this version include enough contiguous safe characters blocks to reach the 131586 required for base131072?

**Comment by qntm** [comment]
Contiguous blocks, almost certainly not. But yes, Unicode 16.0.0 has 134,513 ["safe"](https://qntm.org/safe) characters in total, which is just barely enough that we can start trying to figure out Base131072.

Note that the majority of this encoding is going to be the 128kB lookup table. Storing that lookup table in an efficient way is going to be the interesting part I think.

**Comment by PhMajerus** [comment]
I didn't mean 131586 contiguous at once, but I guess we should try to find the largest blocks size possible to minimize the lookup table, so maybe an automated process to try 131072/(2^x), increasing x until we find (2^x) blocks in Unicode 16.0, and hoping it won't be 8192 blocks of 16 contiguous characters.
If it gets too bad, I guess using some logic to use the largest possible blocks of unequal sizes instead of a simple lookup table is a solution too.

**Comment by PhMajerus** [comment]
With only 134513 safe characters and needing 131586, I guess a simple lookup table that tries to group sequences of characters to reduce its size won't be possible. Maybe something like actual code that uses the largest possible blocks of unequal sizes could work?
